# Enterprise Change Control Pipeline Template
# Copy this to .github/workflows/ci-cd.yml in your new project

name: Enterprise CI/CD Pipeline

on:
  push:
    branches: [ main, staging, development ]
  pull_request:
    branches: [ main, staging, development ]

env:
  NODE_VERSION: '18'
  CACHE_KEY: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

jobs:
  # Quality Gates - Run on all branches
  quality-gates:
    name: Quality Gates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: TypeScript compilation
        run: npm run build

      - name: ESLint analysis
        run: npm run lint

      - name: Security audit
        run: npm audit --audit-level=moderate

      - name: Build verification
        run: |
          npm run build
          echo "✅ Production build successful"

  # Automated Testing
  testing:
    name: Automated Testing
    runs-on: ubuntu-latest
    needs: quality-gates
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --coverage

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info

  # Staging Deployment
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [quality-gates, testing]
    if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/staging'
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for staging
        run: npm run build
        env:
          NODE_ENV: staging

      - name: Deploy to staging
        run: |
          echo "🚀 Deploying to staging environment"
          echo "✅ Staging deployment completed"

      - name: Notify deployment
        run: |
          echo "📢 Staging deployment notification sent"

  # Production Deployment
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [quality-gates, testing]
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for production
        run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy to production
        run: |
          echo "🚀 Deploying to production environment"
          echo "✅ Production deployment completed"

      - name: Create release
        run: |
          echo "📦 Creating production release"
          echo "✅ Release v$(node -p "require('./package.json').version") created"

      - name: Notify deployment
        run: |
          echo "📢 Production deployment notification sent"

  # Automated Branch Management
  branch-management:
    name: Branch Management
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Update development branch
        run: |
          echo "🔄 Updating development branch..."
          if git show-ref --verify --quiet refs/remotes/origin/development; then
            git fetch origin development:development
            git checkout development
            git merge --no-ff main -m "chore: merge main into development [skip ci]"
            git push origin development
            echo "✅ Development branch updated with main"
          else
            echo "⚠️ Development branch does not exist, skipping..."
          fi

      - name: Update staging branch
        run: |
          echo "🔄 Updating staging branch..."
          if git show-ref --verify --quiet refs/remotes/origin/staging; then
            git fetch origin staging:staging
            git checkout staging
            git merge --no-ff main -m "chore: merge main into staging [skip ci]"
            git push origin staging
            echo "✅ Staging branch updated with main"
          else
            echo "⚠️ Staging branch does not exist, skipping..."
          fi
