# CI/CD Pipeline Template for Python Projects
# Copy this to .github/workflows/ci-cd.yml in your Python project

name: CI/CD Pipeline

on:
  push:
    branches: [ main, staging, development ]
  pull_request:
    branches: [ main, staging, development ]

env:
  PYTHON_VERSION: '3.12'

jobs:
  # Quality Gates - Run on all branches
  quality-gates:
    name: Quality Gates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          if [ -f setup.py ]; then
            pip install -e .
          fi

      - name: Verify Python syntax
        run: |
          echo "✅ Checking Python syntax..."
          python -m py_compile **/*.py || echo "No Python files found"
          echo "✅ Python syntax check passed"

      - name: Run linting (if configured)
        run: |
          if command -v flake8 &> /dev/null; then
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          fi
          if command -v pylint &> /dev/null; then
            pylint **/*.py || echo "Pylint not configured"
          fi

      - name: Run tests (if configured)
        run: |
          if [ -f pytest.ini ] || [ -d tests ]; then
            pytest --cov --cov-report=xml || echo "Tests not configured"
          fi

      - name: Check documentation
        run: |
          echo "✅ Verifying documentation..."
          test -f README.md || echo "Warning: README.md not found"
          test -f CHANGELOG.md || echo "Warning: CHANGELOG.md not found"
          echo "✅ Documentation check completed"

  # Staging Deployment
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: quality-gates
    if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/staging'
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to staging
        run: |
          echo "🚀 Deploying to staging environment"
          # Add your staging deployment commands here
          echo "✅ Staging deployment completed"

  # Production Deployment
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: quality-gates
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to production
        run: |
          echo "🚀 Deploying to production environment"
          # Add your production deployment commands here
          echo "✅ Production deployment completed"

      - name: Create release tag
        run: |
          echo "📦 Creating release tag"
          # Add release creation logic here
          echo "✅ Release created"
